"""Generate the C++ patch table for the v84 HD edits\\ DLL.

Emits loader/hd_patches.inc -- one row per VERIFIED patch, with the value expressed
as a formula in the runtime resolution rather than a baked constant, so the DLL stays
configurable from an ini without regenerating anything.

The formula is fitted, not parsed: every Ezorsia value expression is evaluated at four
resolutions and solved for  value = (aW*W + aH*H)/2 + aWH*W*H + k  (halves because the
only division in the whole set is /2). A row whose fit does not reproduce all four
samples exactly is emitted as a plain constant and flagged -- that is the honest
fallback, and there are only a handful.

    python tools/hd/gen_loader.py
"""
import json
import os
import re
import sys
from fractions import Fraction

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import extract                                   # noqa: E402
import paths                                     # noqa: E402

SAMPLES = [(800, 600), (1280, 720), (1600, 900), (1920, 1080)]

KIND = {'WriteInt': 'K_INT', 'WriteByte': 'K_BYTE', 'WriteShort': 'K_SHORT',
        'WriteDouble': 'K_DOUBLE', 'FillBytes': 'K_FILL', 'WriteString': 'K_STR',
        'WriteByteArray': 'K_BYTES', 'CodeCave': 'K_CAVE'}


def fit(vals):
    """Solve value = aW*W/2 + aH*H/2 + aWH*W*H + k over the four samples."""
    if any(not isinstance(v, int) for v in vals):
        return None
    rows = [[Fraction(w, 2), Fraction(h, 2), Fraction(w * h), Fraction(1), Fraction(v)]
            for (w, h), v in zip(SAMPLES, vals)]
    n = 4
    for c in range(n):                                     # gaussian elimination
        p = next((r for r in range(c, n) if rows[r][c]), None)
        if p is None:
            continue
        rows[c], rows[p] = rows[p], rows[c]
        rows[c] = [x / rows[c][c] for x in rows[c]]
        for r in range(n):
            if r != c and rows[r][c]:
                f = rows[r][c]
                rows[r] = [a - f * b for a, b in zip(rows[r], rows[c])]
    sol = []
    for c in range(n):
        if rows[c][c] == 0:
            if rows[c][n]:
                return None
            sol.append(Fraction(0))
        else:
            sol.append(rows[c][n])
    if any(x.denominator != 1 for x in sol):
        return None
    aW, aH, aWH, k = (int(x) for x in sol)
    for (w, h), v in zip(SAMPLES, vals):
        if aW * w // 2 + aH * h // 2 + aWH * w * h + k != v:
            return None
    return aW, aH, aWH, k


def main():
    tables = [extract.build(w, h) for w, h in SAMPLES]
    base = json.load(open(paths.PATCHES))['patches']
    J = json.load(open(os.path.join(paths.DATA, 'v84-patchset.json')))
    rows = {r['id']: r for r in J['rows']}

    # Emit the SHIPPING set only. Groups A (anti-tamper/CRC), B (server IP) and L
    # (window mode) are already done by the existing edits\ DLLs -- bypass, redirect,
    # window-mode. Emitting them here would put two writers on the same functions,
    # which is the exact failure this design exists to avoid, and group B would fight
    # redirect-1.0.0.dll over the server address. K is optional gameplay caps.
    skip_groups = set(J['drop_groups']) | set(J['optional_groups'])

    out, nfit, nconst, skipped, nadj = [], 0, 0, 0, 0
    for i, p in enumerate(base):
        r = rows.get(p['id'])
        if not r or r['verdict'] != 'PASS' or r['group'] in skip_groups:
            skipped += 1
            continue
        vals = [t[i]['value'] for t in tables]
        f = fit(vals)
        # VANILLA DRIFT. Ezorsia's value is tuned to the v83 literal at this site --
        # `m_nGameHeight - 92` is really `508 + H - 600`, where 508 is v83's own constant.
        # Where v84 shipped a different literal, writing Ezorsia's number unchanged moves
        # the widget by exactly the difference. Subtracting the drift from the constant
        # term preserves the offset Ezorsia applied, measured against each image's own
        # baseline. verify.py computes the drift; see its VANILLA DRIFT table and the
        # README for which of these are proven and which are intent-preserving guesses.
        adj = r.get('van_adjust') or 0
        if f:
            nfit += 1
            aW, aH, aWH, k = f
            expr = f'{{{aW},{aH},{aWH},{k - adj}}}'
        else:
            nconst += 1
            v = p['value']
            k = v if isinstance(v, int) else 0
            expr = f'{{0,0,0,{k - adj}}}'
        if adj:
            nadj += 1
        out.append((r, p, expr, bool(f), adj))

    os.makedirs(os.path.join(paths.HD, 'loader'), exist_ok=True)
    dst = os.path.join(paths.HD, 'loader', 'hd_patches.inc')
    with open(dst, 'w') as f:
        f.write('// GENERATED by tools/hd/gen_loader.py -- do not edit by hand.\n'
                '// Every row here passed tools/hd/verify.py against BOTH v84 memory dumps:\n'
                '//   the address exists, the bytes decode to the same instruction shape as\n'
                '//   the v83 site, and the write lands on that instruction\'s own operand.\n'
                '// value = aW*W/2 + aH*H/2 + aWH*W*H + k\n'
                '// expect[] is what these bytes read in the VERIFIED v84 image. The DLL\n'
                '// compares before it writes, so a client that is not the one this table\n'
                '// was checked against gets skipped instead of corrupted.\n'
                '// { v84addr, size, kind, {aW,aH,aWH,k}, group, id, v83addr, nexp, {exp} }\n'
                'static const HdPatch kHdPatches[] = {\n')
        for r, p, expr, fitted, adj in out:
            note = p['comment'].replace('\n', ' ').replace('*/', '* /')[:60]
            eb = bytes.fromhex(r.get('expect') or '')
            ex = '{' + ','.join(f'0x{b:02X}' for b in eb) + '}' if eb else '{0}'
            f.write(f'  {{ 0x{r["v84"]:08X}, {r.get("size84", r["size"]):3}, '
                    f'{KIND[r["op"]]:8}, {expr:>18},'
                    f" '{r['group']}', \"{r['id']}\", 0x{r['v83']:08X},"
                    f' {len(eb)}, {ex} }},'
                    f'{"" if fitted else "  // CONST (non-linear)"}'
                    f'{f"  // VANILLA-ADJ {adj:+d}" if adj else ""}'
                    f'  // {note}\n')
        f.write('};\n')
        cave = [(r, p) for r, p, _, _, _ in out if r['op'] == 'CodeCave']
        f.write('\n// Code-cave origins and return addresses. codecaves.h from upstream is\n'
                '// used VERBATIM except for the bodies marked BODY EDIT below.\n')
        nedit = 0
        for r, p in cave:
            nm = p.get('cave', 'CAVE')
            n = r.get('size84', r['size'])
            f.write(f'#define HD_{nm}_ORIGIN 0x{r["v84"]:08X}\n')
            f.write(f'#define HD_{nm}_RETN   0x{r["v84"] + n:08X}'
                    f'  // origin + {n} ({n - 5} nops after the 5-byte jmp)\n')
            # A cave body REPLAYS what it displaced. Any [esi+disp] baked into that body
            # has to move with v84's struct layout, so emit the v84 displacement as a
            # constant rather than leaving the v83 literal in the naked asm.
            for s in r.get('cave_v84_seq', []):
                m = re.search(r'\[esi \+ (0x[0-9a-f]+)\]', s)
                if m:
                    f.write(f'#define HD_{nm}_MEMBER 0x{m.group(1)[2:].upper()}'
                            f'  // v84 CUIStatusBar member; v83 literal in the body is stale\n')
            if not r.get('cave_body_same', True):
                nedit += 1
                f.write(f'// BODY EDIT REQUIRED for {nm}:\n')
                f.write(f'//   v83 displaced: {" ; ".join(r.get("cave_v83_seq", []))}\n')
                f.write(f'//   v84 displaced: {" ; ".join(r.get("cave_v84_seq", []))}\n')

        # codecaves.h is vendored from upstream VERBATIM (bar two body edits) and its asm
        # jumps through Ezorsia's own `dwXxxRetn` names. Bind each to the v84 address we
        # resolved, so the header needs no find-and-replace. Caves we do not ship bind to
        # 0: their bodies still compile, but nothing ever writes a jmp to them, so they
        # are unreachable dead code rather than a hazard.
        f.write('\n// Ezorsia`s own return-address symbol names, bound to v84.\n')
        shipped = {p['id'] for p in base if rows.get(p['id'], {}).get('verdict') == 'PASS'}
        seen = set()
        for p in base:
            if p['op'] != 'CodeCave' or p['retn_const'] in seen:
                continue
            seen.add(p['retn_const'])
            r = rows.get(p['id'])
            if p['id'] in shipped and r and r['group'] not in skip_groups:
                v = f'0x{r["v84"] + (r.get("size84") or r["size"]):08X}'
                why = f'{p["cave"]}'
            else:
                v, why = '0', f'{p["cave"]} NOT SHIPPED - unreachable'
            f.write(f'const unsigned long {p["retn_const"]} = {v};  // {why}\n')

    # X-macro list of the shipped caves, expanded by dllmain.cpp into the apply table.
    dst2 = os.path.join(paths.HD, 'loader', 'hd_caves.inc')
    with open(dst2, 'w') as f:
        f.write('// GENERATED by tools/hd/gen_loader.py -- do not edit by hand.\n'
                '// HD_CAVE(<codecaves.h function>, <patch row id>)\n')
        for r, p in cave:
            f.write(f'HD_CAVE({p["cave"]}, "{p["id"]}")\n')
    print(f'wrote {dst2}')
    print(f'wrote {dst}')
    print(f'  rows: {len(out)}   formula-fitted: {nfit}   baked constant: {nconst}')
    print(f'  skipped (not PASS): {skipped}')
    print(f"  code caves: {len(cave)}   needing a BODY edit: {nedit}")
    print(f"  rows with a vanilla-drift adjustment: {nadj}")


if __name__ == '__main__':
    main()
