"""Generate the C++ patch table for the v84 HD edits\\ DLL.

Emits loader/hd_patches.inc -- one row per VERIFIED patch, with the value expressed
as a formula in the runtime resolution rather than a baked constant, so the DLL stays
configurable from an ini without regenerating anything.

The formula is fitted, not parsed: every Ezorsia value expression is evaluated at four
resolutions and solved for  value = (aW*W + aH*H)/2 + aWH*W*H + k  (halves because the
only division in the whole set is /2). A row whose fit does not reproduce all four
samples exactly is emitted as a plain constant and flagged -- that is the honest
fallback, and there are only a handful.

    python tools/hd/gen_loader.py
"""
import json
import os
import sys
from fractions import Fraction

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import extract                                   # noqa: E402
import paths                                     # noqa: E402

SAMPLES = [(800, 600), (1280, 720), (1600, 900), (1920, 1080)]

KIND = {'WriteInt': 'K_INT', 'WriteByte': 'K_BYTE', 'WriteShort': 'K_SHORT',
        'WriteDouble': 'K_DOUBLE', 'FillBytes': 'K_FILL', 'WriteString': 'K_STR',
        'WriteByteArray': 'K_BYTES', 'CodeCave': 'K_CAVE'}


def fit(vals):
    """Solve value = aW*W/2 + aH*H/2 + aWH*W*H + k over the four samples."""
    if any(not isinstance(v, int) for v in vals):
        return None
    rows = [[Fraction(w, 2), Fraction(h, 2), Fraction(w * h), Fraction(1), Fraction(v)]
            for (w, h), v in zip(SAMPLES, vals)]
    n = 4
    for c in range(n):                                     # gaussian elimination
        p = next((r for r in range(c, n) if rows[r][c]), None)
        if p is None:
            continue
        rows[c], rows[p] = rows[p], rows[c]
        rows[c] = [x / rows[c][c] for x in rows[c]]
        for r in range(n):
            if r != c and rows[r][c]:
                f = rows[r][c]
                rows[r] = [a - f * b for a, b in zip(rows[r], rows[c])]
    sol = []
    for c in range(n):
        if rows[c][c] == 0:
            if rows[c][n]:
                return None
            sol.append(Fraction(0))
        else:
            sol.append(rows[c][n])
    if any(x.denominator != 1 for x in sol):
        return None
    aW, aH, aWH, k = (int(x) for x in sol)
    for (w, h), v in zip(SAMPLES, vals):
        if aW * w // 2 + aH * h // 2 + aWH * w * h + k != v:
            return None
    return aW, aH, aWH, k


def main():
    tables = [extract.build(w, h) for w, h in SAMPLES]
    base = json.load(open(paths.PATCHES))['patches']
    J = json.load(open(os.path.join(paths.DATA, 'v84-patchset.json')))
    rows = {r['id']: r for r in J['rows']}

    out, nfit, nconst, skipped = [], 0, 0, 0
    for i, p in enumerate(base):
        r = rows.get(p['id'])
        if not r or r['verdict'] != 'PASS':
            skipped += 1
            continue
        vals = [t[i]['value'] for t in tables]
        f = fit(vals)
        if f:
            nfit += 1
            aW, aH, aWH, k = f
            expr = f'{{{aW},{aH},{aWH},{k}}}'
        else:
            nconst += 1
            v = p['value']
            k = v if isinstance(v, int) else 0
            expr = f'{{0,0,0,{k}}}'
        out.append((r, p, expr, bool(f)))

    os.makedirs(os.path.join(paths.HD, 'loader'), exist_ok=True)
    dst = os.path.join(paths.HD, 'loader', 'hd_patches.inc')
    with open(dst, 'w') as f:
        f.write('// GENERATED by tools/hd/gen_loader.py -- do not edit by hand.\n'
                '// Every row here passed tools/hd/verify.py against BOTH v84 memory dumps:\n'
                '//   the address exists, the bytes decode to the same instruction shape as\n'
                '//   the v83 site, and the write lands on that instruction\'s own operand.\n'
                '// value = aW*W/2 + aH*H/2 + aWH*W*H + k\n'
                '// { v84addr, size, kind, {aW,aH,aWH,k}, group, id, v83addr }\n'
                'static const HdPatch kHdPatches[] = {\n')
        for r, p, expr, fitted in out:
            note = p['comment'].replace('\n', ' ').replace('*/', '* /')[:60]
            f.write(f'  {{ 0x{r["v84"]:08X}, {r["size"]:3}, {KIND[r["op"]]:8}, {expr:>18},'
                    f" '{r['group']}', \"{r['id']}\", 0x{r['v83']:08X} }},"
                    f'{"" if fitted else "  // CONST (non-linear)"}'
                    f'  // {note}\n')
        f.write('};\n')
        cave = [(r, p) for r, p, _, _ in out if r['op'] == 'CodeCave']
        f.write('\n// Code-cave return addresses. codecaves.h from upstream is used\n'
                '// VERBATIM; only these constants change for v84.\n')
        for r, p in cave:
            f.write(f'#define HD_{p.get("cave", "CAVE")}_ORIGIN 0x{r["v84"]:08X}\n')
            f.write(f'#define HD_{p.get("cave", "CAVE")}_RETN   '
                    f'0x{r["v84"] + r["size"]:08X}  // origin + {r["size"]} nops\n')
    print(f'wrote {dst}')
    print(f'  rows: {len(out)}   formula-fitted: {nfit}   baked constant: {nconst}')
    print(f'  skipped (not PASS): {skipped}')
    print(f'  code caves with generated origin/retn: {len(cave)}')


if __name__ == '__main__':
    main()
