package tools.packetvalidator;

import java.util.List;

/**
 * What the client DECODES for one server-&gt;client opcode: an ordered list of
 * {@code CInPacket::Decode*} calls, one per field.
 *
 * <p>A model is only useful if it is <em>exact</em>. Nothing here guesses: models are generated by
 * {@code tools/v84/derive-decode-models.py} from the hand-annotated gms_v83 IDA export with the
 * proven v84 deltas applied, and each records where it came from in {@link #source()}. An opcode
 * with a conditional or data-driven body has no model at all rather than a wrong one - see that
 * script for the covered / rejected lists and the reasons.
 */
public record DecodeModel(String opcode, String source, List<DecodeModel.Field> fields) {

    /** One {@code CInPacket::Decode*} call. {@code count} is meaningful only for {@link Kind#BUF}. */
    public record Field(String name, Kind kind, int count) {
    }

    public enum Kind {
        /** Decode1 */
        U8(1),
        /** Decode2 */
        U16(2),
        /** Decode4 */
        U32(4),
        /** Decode8 */
        U64(8),
        /** DecodeStr: a Decode2 length followed by that many bytes */
        STR(-1),
        /** DecodeBuf(n): n raw bytes, n known statically */
        BUF(-1);

        final int width;

        Kind(int width) {
            this.width = width;
        }
    }
}
