/*
	This file is part of the OdinMS Maple Story Server
    Copyright (C) 2008 Patrick Huy <patrick.huy@frz.cc>
		       Matthias Butz <matze@odinms.de>
		       Jan Christian Meyer <vimes@odinms.de>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation version 3 as published by
    the Free Software Foundation. You may not use, modify or distribute
    this program under any other version of the GNU Affero General Public
    License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
package net.opcodes;

public enum RecvOpcode {
    CUSTOM_PACKET,//13 37 lol

    LOGIN_PASSWORD,
    GUEST_LOGIN,
    SERVERLIST_REREQUEST,
    CHARLIST_REQUEST,
    SERVERSTATUS_REQUEST,
    ACCEPT_TOS,
    SET_GENDER,
    AFTER_LOGIN,
    REGISTER_PIN,
    SERVERLIST_REQUEST,
    PLAYER_DC,
    VIEW_ALL_CHAR,
    PICK_ALL_CHAR,
    NAME_TRANSFER,
    WORLD_TRANSFER,
    CHAR_SELECT,
    PLAYER_LOGGEDIN,
    CHECK_CHAR_NAME,
    CREATE_CHAR,
    DELETE_CHAR,
    PONG,
    CLIENT_START_ERROR,
    CLIENT_ERROR,
    STRANGE_DATA,
    RELOG,
    REGISTER_PIC,
    CHAR_SELECT_WITH_PIC,
    VIEW_ALL_PIC_REGISTER,
    VIEW_ALL_WITH_PIC,
    CHANGE_MAP,
    CHANGE_CHANNEL,
    ENTER_CASHSHOP,
    MOVE_PLAYER,
    CANCEL_CHAIR,
    USE_CHAIR,
    CLOSE_RANGE_ATTACK,
    RANGED_ATTACK,
    MAGIC_ATTACK,
    TOUCH_MONSTER_ATTACK,
    TAKE_DAMAGE,
    GENERAL_CHAT,
    CLOSE_CHALKBOARD,
    FACE_EXPRESSION,
    USE_ITEMEFFECT,
    USE_DEATHITEM,
    MOB_BANISH_PLAYER,
    MONSTER_BOOK_COVER,
    NPC_TALK,
    REMOTE_STORE,
    NPC_TALK_MORE,
    NPC_SHOP,
    STORAGE,
    HIRED_MERCHANT_REQUEST,
    FREDRICK_ACTION,
    DUEY_ACTION,
    OWL_ACTION,   //sends most searched info to client
    OWL_WARP,     //handles player warp to store
    ADMIN_SHOP,
    ITEM_SORT,
    ITEM_SORT2,
    ITEM_MOVE,
    USE_ITEM,
    CANCEL_ITEM_EFFECT,
    USE_SUMMON_BAG,
    PET_FOOD,
    USE_MOUNT_FOOD,
    SCRIPTED_ITEM,
    USE_CASH_ITEM,
    //USE_OWL_ITEM(0x50), ... no idea
    USE_CATCH_ITEM,
    USE_SKILL_BOOK,
    USE_TELEPORT_ROCK,
    USE_RETURN_SCROLL,
    USE_UPGRADE_SCROLL,
    DISTRIBUTE_AP,
    AUTO_DISTRIBUTE_AP,
    HEAL_OVER_TIME,
    DISTRIBUTE_SP,
    SPECIAL_MOVE,
    CANCEL_BUFF,
    SKILL_EFFECT,
    MESO_DROP,
    GIVE_FAME,
    CHAR_INFO_REQUEST,
    SPAWN_PET,
    CANCEL_DEBUFF,
    CHANGE_MAP_SPECIAL,
    USE_INNER_PORTAL,
    TROCK_ADD_MAP,
    REPORT,
    QUEST_ACTION,
    //USER_CALC_DAMAGE_STAT_SET_REQUEST(0x6C),
    GRENADE_EFFECT,
    SKILL_MACRO,
    USE_ITEM_REWARD,
    MAKER_SKILL,
    USE_REMOTE,
    WATER_OF_LIFE,
    ADMIN_CHAT,
    MULTI_CHAT,
    WHISPER,
    SPOUSE_CHAT,
    MESSENGER,
    PLAYER_INTERACTION,
    PARTY_OPERATION,
    DENY_PARTY_REQUEST,
    GUILD_OPERATION,
    DENY_GUILD_REQUEST,
    ADMIN_COMMAND,
    ADMIN_LOG,
    BUDDYLIST_MODIFY,
    NOTE_ACTION,
    USE_DOOR,
    CHANGE_KEYMAP,
    RPS_ACTION,
    RING_ACTION,
    WEDDING_ACTION,
    WEDDING_TALK,
    WEDDING_TALK_MORE,
    ALLIANCE_OPERATION,
    DENY_ALLIANCE_REQUEST,
    OPEN_FAMILY_PEDIGREE,
    OPEN_FAMILY,
    ADD_FAMILY,
    SEPARATE_FAMILY_BY_SENIOR,
    SEPARATE_FAMILY_BY_JUNIOR,
    ACCEPT_FAMILY,
    USE_FAMILY,
    CHANGE_FAMILY_MESSAGE,
    FAMILY_SUMMON_RESPONSE,
    BBS_OPERATION,
    ENTER_MTS,
    USE_SOLOMON_ITEM,
    USE_GACHA_EXP,
    NEW_YEAR_CARD_REQUEST,
    CASHSHOP_SURPRISE,
    CLICK_GUIDE,
    ARAN_COMBO_COUNTER,
    MOVE_PET,
    PET_CHAT,
    PET_COMMAND,
    PET_LOOT,
    PET_AUTO_POT,
    PET_EXCLUDE_ITEMS,
    MOVE_SUMMON,
    SUMMON_ATTACK,
    DAMAGE_SUMMON,
    BEHOLDER,
    MOVE_DRAGON,
    CHANGE_QUICKSLOT,//CP_QuickslotKeyMappedModified
    MOVE_LIFE,
    AUTO_AGGRO,
    FIELD_DAMAGE_MOB,
    MOB_DAMAGE_MOB_FRIENDLY,
    MONSTER_BOMB,
    MOB_DAMAGE_MOB,
    NPC_ACTION,
    ITEM_PICKUP,
    DAMAGE_REACTOR,
    TOUCHING_REACTOR,
    PLAYER_MAP_TRANSFER,
    MAPLETV,//Don't know
    SNOWBALL,
    LEFT_KNOCKBACK,
    COCONUT,
    MATCH_TABLE,//Would be cool if I ever get it to work :)
    MONSTER_CARNIVAL,
    PARTY_SEARCH_REGISTER,
    PARTY_SEARCH_START,
    PARTY_SEARCH_UPDATE,
    CHECK_CASH,
    CASHSHOP_OPERATION,
    COUPON_CODE,
    OPEN_ITEMUI,
    CLOSE_ITEMUI,
    USE_ITEMUI,
    MTS_OPERATION,
    USE_MAPLELIFE,
    USE_HAMMER;

    // Values come from resources/opcodes/recvops-NN.properties - see OpcodeTable.
    // name() is safe here: Enum's constructor has already set it by the time this initialiser runs.
    private final int code = OpcodeTable.recv(name());

    public int getValue() {
        return code;
    }
}
