"""Generate scroll_prices.h -- the client-side copy of the server's scroll sell prices.

The client draws the Sell tab from CItemInfo::GetItemPrice, which reads info/price out of its
own Item.wz.  That file is the owner's, packed, and read-only, so the number is corrected at
runtime instead -- but the cave only ever has an itemId in hand, not the success rate.  Hence a
baked table.

There is exactly ONE source of truth for the prices, and it is the server:
constants/inventory/ItemConstants.java.  This script parses the tier map and the GM scroll set
straight out of it and joins them against wz/Item.wz/Consume/0204.img.xml, so the two sides
cannot drift -- change a tier in the Java and re-run this, and the client follows.

    python tools/hd/loader/gen_scroll_prices.py

Writes tools/hd/loader/scroll_prices.h.  Re-run it whenever ItemConstants or 0204.img changes;
ScrollSellPriceTest pins the Java half.
"""

import bisect
import io
import os
import re
import xml.etree.ElementTree as ET

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..', '..'))
JAVA = os.path.join(ROOT, 'src', 'main', 'java', 'constants', 'inventory', 'ItemConstants.java')
WZ = os.path.join(ROOT, 'wz', 'Item.wz', 'Consume', '0204.img.xml')
OUT = os.path.join(HERE, 'scroll_prices.h')

TABLETS_SUCCESS = 70   # 2047xxx table their odds in info/successRates; 70% on an untouched equip


def read_java():
    text = io.open(JAVA, encoding='utf-8').read()
    body = text[text.index('SCROLL_SELL_PRICE'):text.index('scrollSellPrice')]
    tiers = {int(s): int(p.replace('_', '')) for s, p in
             re.findall(r'Map\.entry\((\d+),\s*([\d_]+)\)', body)}
    gm_body = text[text.index('GM_SCROLLS'):text.index('GM_SCROLL_PRICE')]
    gm = {int(x) for x in re.findall(r'\b(20\d{5})\b', gm_body)}
    gm_price = int(re.search(r'GM_SCROLL_PRICE\s*=\s*([\d_]+)', text).group(1).replace('_', ''))
    if not tiers or not gm:
        raise SystemExit('could not parse ItemConstants.java')
    return tiers, gm, gm_price


def tier_price(tiers, success):
    """Nearest listed tier, ties toward the lower odds -- ItemConstants.scrollSellPrice."""
    if success in tiers:
        return tiers[success]
    keys = sorted(tiers)
    i = bisect.bisect_left(keys, success)
    lo = keys[i - 1] if i > 0 else None
    hi = keys[i] if i < len(keys) else None
    if lo is None:
        return tiers[hi]
    if hi is None:
        return tiers[lo]
    return tiers[lo] if success - lo <= hi - success else tiers[hi]


def main():
    tiers, gm, gm_price = read_java()
    rows = []
    for item in ET.parse(WZ).getroot():
        item_id = int(item.get('name'))
        info = item.find("imgdir[@name='info']")
        success = None
        for child in info if info is not None else []:
            if child.get('name') == 'success':
                success = int(child.get('value'))
        price = gm_price if item_id in gm else tier_price(
            tiers, TABLETS_SUCCESS if success is None else success)
        rows.append((item_id, price))
    rows.sort()

    missing = gm - {i for i, _ in rows}
    if missing:
        raise SystemExit('GM scrolls not in 0204.img: %s' % sorted(missing))

    with io.open(OUT, 'w', encoding='ascii', newline='\n') as f:
        f.write('// GENERATED by tools/hd/loader/gen_scroll_prices.py -- do not edit by hand.\n')
        f.write('// Source of truth: constants/inventory/ItemConstants.java + '
                'wz/Item.wz/Consume/0204.img.xml\n')
        f.write('// %d scrolls; tiers %s; %d GM scrolls at %d.\n'
                % (len(rows), ' '.join('%d%%=%d' % t for t in sorted(tiers.items(), reverse=True)),
                   len(gm), gm_price))
        f.write('#pragma once\n\nstruct ScrollPrice { int id; int price; };\n\n')
        f.write('// Sorted by id -- ScrollSellPrice() binary-searches it.\n')
        f.write('static const ScrollPrice kScrollPrices[] = {\n')
        for i in range(0, len(rows), 4):
            f.write('    ' + ' '.join('{%d,%d},' % r for r in rows[i:i + 4]) + '\n')
        f.write('};\n')
    print('wrote %s: %d scrolls, %d GM' % (OUT, len(rows), len(gm)))


if __name__ == '__main__':
    main()
